stages:
- stage: terraforminstall
  displayName: Terraform Install
  jobs:
  - job: terraforminstall
    displayName: Install Terraform Job
    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.6.0'
